language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mateja/docker-react -f Dockerfile.dev .
script:
  - ls
  - ls src
  - docker run -e CI=true mateja/docker-react yarn test
